"""changed RequestDeadline to Date

Revision ID: 26f5e97f0401
Revises: 
Create Date: 2023-03-27 14:14:22.234774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f5e97f0401'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SoftwareRequest', schema=None) as batch_op:
        batch_op.alter_column('RequestDeadline',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SoftwareRequest', schema=None) as batch_op:
        batch_op.alter_column('RequestDeadline',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
